# Generated by Django 3.2.4 on 2021-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('details', models.CharField(max_length=256, verbose_name='Details')),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
